# SPDX-License-Identifier: Apache-2.0.
# Copyright (C) 2026-present ahrs-monitor project and contributors.

# Project package info section.
[package]
name        = "ahrs-monitor"
version     = "0.1.0"
description = "AHRS cross-platform telemetry station"
authors     = ["Alexander <alkuzindev@gmail.com>"]
repository  = "https://github.com/alkuzin/ahrs-monitor"
license     = "Apache-2.0"
edition     = "2024"

# Project dependencies section.
[dependencies]
