# SPDX-License-Identifier: Apache-2.0.
# Copyright (C) 2026-present ahrs-monitor project and contributors.

# Sets the logging level for the output.
[env]
# The logs will include informational messages, warnings and errors.
RUST_LOG="info"

# Sets the aliases for cargo.
[alias]
# Alias for running AHRS monitor.
monitor = "run --bin ahrs-monitor"
# Alias for running IMU simulator.
sim = "run --bin imu-simulator"
